import { useCallback,useEffect,useState } from "react";
import { ApiError,type OperationsClient } from "../lib/api";
import type { CmsDocumentKey,CmsRevision,CmsState,FaqDocument,FaqItem,PricingDocument,PricingMode } from "../lib/cms-types";
import "./WebsiteView.css";

type SaveState="idle"|"saving"|"saved"|"error"|"conflict";
const modes:PricingMode[]=["exact","from","hourly","custom"];
export function WebsiteView({client}:{client:OperationsClient}){
  const [state,setState]=useState<CmsState|null>(null);const [pricing,setPricing]=useState<PricingDocument|null>(null);const [faqs,setFaqs]=useState<FaqDocument|null>(null);const [history,setHistory]=useState<CmsRevision[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [pricingSave,setPricingSave]=useState<SaveState>("idle");const [faqSave,setFaqSave]=useState<SaveState>("idle");
  const load=useCallback(async()=>{setLoading(true);try{const next=await client.cmsState();setState(next);setPricing(next.documents.pricing?.content??null);setFaqs(next.documents.faqs?.content??null);if(next.initialized){const [pricingHistory,faqHistory]=await Promise.all([client.cmsHistory("pricing"),client.cmsHistory("faqs")]);setHistory([...pricingHistory.revisions,...faqHistory.revisions].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));}setError("");}catch(reason){setError(message(reason));}finally{setLoading(false);}},[client]);
  useEffect(()=>{void load();},[load]);
  function changePricing(next:PricingDocument){setPricing(next);setPricingSave("idle");}
  async function save(key:CmsDocumentKey){const document=key==="pricing"?pricing:faqs;const current=state?.documents[key];const setSave=key==="pricing"?setPricingSave:setFaqSave;if(!document||!current)return;setSave("saving");try{await client.saveCmsDocument(key,current.revisionId,document);setSave("saved");await load();}catch(reason){setSave(reason instanceof ApiError&&reason.status===409?"conflict":"error");setError(message(reason));}}
  async function restore(revision:CmsRevision){const current=state?.documents[revision.documentKey];if(!current)return;if(!window.confirm(`Restore ${revision.documentKey} revision ${revision.sequence} as a new draft revision?`))return;try{await client.restoreCmsRevision(revision.documentKey,current.revisionId,revision.revisionId);await load();}catch(reason){setError(message(reason));}}
  async function downloadSnapshot(){try{const snapshot=await client.cmsSnapshot();const blob=new Blob([JSON.stringify(snapshot,null,2)+"\n"],{type:"application/json"});const anchor=document.createElement("a");anchor.href=URL.createObjectURL(blob);anchor.download=`focus-content-snapshot-${Date.now()}.json`;anchor.click();URL.revokeObjectURL(anchor.href);}catch(reason){setError(message(reason));}}
  if(loading&&!state)return <article className="view"><p>Loading website drafts…</p></article>;
  if(error&&!state)return <article className="view"><h1>Website</h1><p role="alert">{error}</p><button className="button secondary" onClick={()=>void load()}>Try again</button></article>;
  if(!state?.initialized||!pricing||!faqs)return <article className="view website-view"><div><p className="eyebrow">Website</p><h1>Website drafts</h1></div><section className="panel"><h2>Initialization required</h2><p>Import Sunny’s checked-in pricing and FAQs once using the documented local initialization command. Re-running initialization is safe and never replaces an existing draft.</p></section></article>;
  return <article className="view website-view"><div className="view-heading"><div><p className="eyebrow">Website</p><h1>Pricing &amp; FAQs</h1><p>Manage the draft content used for a future immutable website release.</p></div><button className="button secondary" onClick={()=>void downloadSnapshot()}>Export draft snapshot</button></div>
    <div className="cms-live-warning" role="note"><strong>Draft content — not the live website</strong>Saving here records a draft revision only. This milestone does not publish or deploy Sunny.</div>
    {error?<p className="inline-error" role="alert">{error}</p>:null}
    <section className="panel"><h2>Pricing draft</h2><p className="help-text">Stable identifiers keep existing page and inquiry references intact. This milestone supports labels, amounts, and pricing modes; adding, deleting, or reordering pricing services remains a development task.</p><div className="cms-pricing-list">{Object.entries(pricing.values).map(([id,item])=><div className="cms-pricing-row" key={id}><label>Label<input value={item.label} onChange={(event)=>changePricing({...pricing,values:{...pricing.values,[id]:{...item,label:event.target.value}}})}/><code>{id}</code></label><label>Amount (USD)<input type="number" min="0" step="1" value={item.amount} onChange={(event)=>changePricing({...pricing,values:{...pricing.values,[id]:{...item,amount:Number(event.target.value)}}})}/></label><label>Pricing mode<select value={item.mode} onChange={(event)=>changePricing({...pricing,values:{...pricing.values,[id]:{...item,mode:event.target.value as PricingMode}}})}>{modes.map((mode)=><option value={mode} key={mode}>{modeLabel(mode)}</option>)}</select></label></div>)}</div><SaveBar state={pricingSave} onSave={()=>void save("pricing")}/></section>
    <FaqEditor title="Common FAQs" items={faqs.common} onChange={(common)=>{setFaqs({...faqs,common});setFaqSave("idle");}}/><FaqEditor title="Pricing FAQs" items={faqs.pricing} onChange={(pricingItems)=>{setFaqs({...faqs,pricing:pricingItems});setFaqSave("idle");}}/><SaveBar state={faqSave} onSave={()=>void save("faqs")}/>
    <section className="panel"><div className="cms-history-header"><div><h2>Revision history</h2><p className="help-text">Restore creates a new draft revision; history is never rewritten.</p></div><button className="button text" onClick={()=>void load()}>Refresh</button></div><div className="cms-history-list">{history.map((revision)=><div className="cms-history-row" key={revision.revisionId}><div><strong>{revision.documentKey==="pricing"?"Pricing":"FAQs"} · revision {revision.sequence}</strong><p>{new Date(revision.createdAt).toLocaleString()} · {revision.actor.displayName}{revision.restoredFromRevisionId?" · restored":""}</p></div><button className="button secondary" disabled={state.documents[revision.documentKey]?.revisionId===revision.revisionId} onClick={()=>void restore(revision)}>Restore as new draft</button></div>)}</div></section>
  </article>;
}
function FaqEditor({title,items,onChange}:{title:string;items:FaqItem[];onChange:(items:FaqItem[])=>void}){function move(index:number,direction:-1|1){const target=index+direction;if(target<0||target>=items.length)return;const next=[...items];[next[index],next[target]]=[next[target]!,next[index]!];onChange(next);}return <section className="panel"><h2>{title}</h2><div className="cms-faq-list">{items.map((item,index)=><div className="cms-faq-card" key={item.id}><label>Question<input value={item.question} onChange={(event)=>onChange(items.map((value)=>value.id===item.id?{...value,question:event.target.value}:value))}/></label><label>Answer<textarea value={item.answer} onChange={(event)=>onChange(items.map((value)=>value.id===item.id?{...value,answer:event.target.value}:value))}/></label><div className="cms-row-actions"><button className="button text" disabled={index===0} onClick={()=>move(index,-1)}>Move up</button><button className="button text" disabled={index===items.length-1} onClick={()=>move(index,1)}>Move down</button><button className="button text" onClick={()=>onChange(items.filter((value)=>value.id!==item.id))}>Remove</button></div></div>)}</div><button className="button secondary" onClick={()=>onChange([...items,{id:`faq_${crypto.randomUUID().replaceAll("-","")}`,question:"",answer:""}])}>Add FAQ</button></section>;}
function SaveBar({state,onSave}:{state:SaveState;onSave:()=>void}){const text=state==="saving"?"Saving…":state==="saved"?"Saved as a new draft revision.":state==="conflict"?"Conflict: a newer draft exists. Refresh before saving again.":state==="error"?"Draft was not saved.":"";return <div className="cms-actions"><p className={`cms-status ${state}`} role="status" aria-live="polite">{text}</p><button className="button primary" disabled={state==="saving"} onClick={onSave}>Save draft</button></div>;}
function modeLabel(mode:PricingMode){return{exact:"Flat price",from:"Starting at",hourly:"Per hour",custom:"Custom quote"}[mode];}
function message(reason:unknown){return reason instanceof Error?reason.message:"The website draft request failed.";}
