import { useCallback,useEffect,useState,type Dispatch,type SetStateAction } from "react";
import { ApiError,type OperationsClient } from "../lib/api";
import type { CmsContent,CmsDocumentKey,CmsRevision,FaqDocument,FaqItem,PricingDocument,PricingMode } from "../lib/cms-types";
import "./WebsiteView.css";

type EditorStatus="saved"|"unsaved"|"saving"|"conflict"|"error";
type EditorAction="save"|"reload"|"restore"|null;
type DocumentEditor<T extends CmsContent>={base:CmsRevision<T>;draft:T;dirty:boolean;status:EditorStatus;action:EditorAction;message:string};
const modes:PricingMode[]=["exact","from","hourly","custom"];

export function WebsiteView({client}:{client:OperationsClient}){
  const [initialized,setInitialized]=useState<boolean|null>(null);const [pricing,setPricing]=useState<DocumentEditor<PricingDocument>|null>(null);const [faqs,setFaqs]=useState<DocumentEditor<FaqDocument>|null>(null);const [history,setHistory]=useState<CmsRevision[]>([]);const [loading,setLoading]=useState(true);const [pageError,setPageError]=useState("");
  const refreshHistory=useCallback(async()=>{try{const [pricingHistory,faqHistory]=await Promise.all([client.cmsHistory("pricing"),client.cmsHistory("faqs")]);setHistory([...pricingHistory.revisions,...faqHistory.revisions].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));setPageError("");}catch(reason){setPageError(message(reason));}},[client]);
  const loadInitial=useCallback(async()=>{setLoading(true);try{const next=await client.cmsState();setInitialized(next.initialized);if(next.documents.pricing)setPricing(editor(next.documents.pricing));if(next.documents.faqs)setFaqs(editor(next.documents.faqs));if(next.initialized)await refreshHistory();else setPageError("");}catch(reason){setPageError(message(reason));}finally{setLoading(false);}},[client,refreshHistory]);
  useEffect(()=>{void loadInitial();},[loadInitial]);
  const hasUnsaved=Boolean(pricing?.dirty||faqs?.dirty);
  useEffect(()=>{if(!hasUnsaved)return;const beforeUnload=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue="";};const internalNavigation=(event:MouseEvent)=>{const target=event.target;if(!(target instanceof Element))return;const anchor=target.closest<HTMLAnchorElement>('a[href^="#/"]');if(!anchor||anchor.getAttribute("href")===window.location.hash)return;if(!window.confirm("You have unsaved website changes. Leave this editor and discard them?")){event.preventDefault();event.stopPropagation();}};window.addEventListener("beforeunload",beforeUnload);document.addEventListener("click",internalNavigation,true);return()=>{window.removeEventListener("beforeunload",beforeUnload);document.removeEventListener("click",internalNavigation,true);};},[hasUnsaved]);

  function editPricing(next:PricingDocument){setPricing((current)=>current?{...current,draft:next,dirty:true,status:"unsaved",action:null,message:"Unsaved changes."}:current);}
  function editFaqs(next:FaqDocument){setFaqs((current)=>current?{...current,draft:next,dirty:true,status:"unsaved",action:null,message:"Unsaved changes."}:current);}
  async function save<T extends CmsContent>(key:CmsDocumentKey,current:DocumentEditor<T>|null,setCurrent:Dispatch<SetStateAction<DocumentEditor<T>|null>>){if(!current||!current.dirty||current.status==="saving")return;const submitted=current.draft;setCurrent((value)=>value?{...value,status:"saving",action:"save",message:"Saving draft…"}:value);try{const result=await client.saveCmsDocument(key,current.base.revisionId,submitted);const saved=result.document as CmsRevision<T>;setCurrent((value)=>{if(!value)return value;const editedDuringSave=value.draft!==submitted;return{base:saved,draft:editedDuringSave?value.draft:saved.content,dirty:editedDuringSave,status:editedDuringSave?"unsaved":"saved",action:null,message:editedDuringSave?"Saved the submitted version. Newer edits remain unsaved.":`Saved as draft revision ${saved.sequence}.`};});void refreshHistory();}catch(reason){const conflict=reason instanceof ApiError&&reason.status===409;setCurrent((value)=>value?{...value,status:conflict?"conflict":"error",action:null,message:conflict?"A newer saved draft exists. Your edits are still here; choose how to recover.":message(reason)}:value);}}
  async function reload<T extends CmsContent>(key:CmsDocumentKey,current:DocumentEditor<T>|null,setCurrent:Dispatch<SetStateAction<DocumentEditor<T>|null>>,force=false){if(!current||current.status==="saving")return;if(current.dirty&&!force&&!window.confirm(`Discard your unsaved ${key==="pricing"?"pricing":"FAQ"} changes and load the latest saved draft?`))return;setCurrent((value)=>value?{...value,status:"saving",action:"reload",message:"Loading the latest saved draft…"}:value);try{const result=await client.cmsDocument(key);setCurrent(editor(result.document as CmsRevision<T>));void refreshHistory();}catch(reason){setCurrent((value)=>value?{...value,status:"error",action:null,message:message(reason)}:value);}}
  async function keepEditsOnLatest<T extends CmsContent>(key:CmsDocumentKey,current:DocumentEditor<T>|null,setCurrent:Dispatch<SetStateAction<DocumentEditor<T>|null>>){if(!current||current.status==="saving")return;setCurrent((value)=>value?{...value,status:"saving",action:"reload",message:"Loading the latest revision while keeping your edits…"}:value);try{const result=await client.cmsDocument(key);setCurrent((value)=>value?{...value,base:result.document as CmsRevision<T>,dirty:true,status:"unsaved",action:null,message:"Your edits are unchanged and now use the latest saved revision as their base. Review them before saving."}:value);void refreshHistory();}catch(reason){setCurrent((value)=>value?{...value,status:"error",action:null,message:message(reason)}:value);}}
  async function restore(revision:CmsRevision){
    if(revision.documentKey==="pricing"){
      if(!pricing||pricing.status==="saving")return;const warning=pricing.dirty?`This will discard your unsaved pricing changes and restore revision ${revision.sequence} as a new saved draft. Continue?`:`Restore pricing revision ${revision.sequence} as a new saved draft?`;if(!window.confirm(warning))return;
      setPricing((value)=>value?{...value,status:"saving",action:"restore",message:`Restoring revision ${revision.sequence}…`}:value);
      try{const result=await client.restoreCmsRevision("pricing",pricing.base.revisionId,revision.revisionId);setPricing(editor(result.document as CmsRevision<PricingDocument>,`Restored revision ${revision.sequence} as a new saved pricing draft.`));await refreshHistory();}catch(reason){const conflict=reason instanceof ApiError&&reason.status===409;setPricing((value)=>value?{...value,status:conflict?"conflict":"error",action:null,message:conflict?"A newer saved draft exists. Your edits are still here; choose how to recover.":message(reason)}:value);}return;
    }
    if(!faqs||faqs.status==="saving")return;const warning=faqs.dirty?`This will discard your unsaved FAQ changes and restore revision ${revision.sequence} as a new saved draft. Continue?`:`Restore FAQ revision ${revision.sequence} as a new saved draft?`;if(!window.confirm(warning))return;
    setFaqs((value)=>value?{...value,status:"saving",action:"restore",message:`Restoring revision ${revision.sequence}…`}:value);
    try{const result=await client.restoreCmsRevision("faqs",faqs.base.revisionId,revision.revisionId);setFaqs(editor(result.document as CmsRevision<FaqDocument>,`Restored revision ${revision.sequence} as a new saved FAQ draft.`));await refreshHistory();}catch(reason){const conflict=reason instanceof ApiError&&reason.status===409;setFaqs((value)=>value?{...value,status:conflict?"conflict":"error",action:null,message:conflict?"A newer saved draft exists. Your edits are still here; choose how to recover.":message(reason)}:value);}
  }
  async function downloadSnapshot(){if(hasUnsaved&&!window.confirm("The snapshot includes saved drafts only. Unsaved form changes will not be exported. Continue?"))return;try{const snapshot=await client.cmsSnapshot();const blob=new Blob([JSON.stringify(snapshot,null,2)+"\n"],{type:"application/json"});const anchor=document.createElement("a");anchor.href=URL.createObjectURL(blob);anchor.download=`focus-content-snapshot-${Date.now()}.json`;anchor.click();URL.revokeObjectURL(anchor.href);setPageError("");}catch(reason){setPageError(message(reason));}}

  if(loading&&initialized===null)return <article className="view"><p>Loading website drafts…</p></article>;
  if(pageError&&initialized===null)return <article className="view"><h1>Website</h1><p role="alert">{pageError}</p><button className="button secondary" onClick={()=>void loadInitial()}>Try again</button></article>;
  if(initialized===false||!pricing||!faqs)return <article className="view website-view"><div><p className="eyebrow">Website</p><h1>Website drafts</h1></div><section className="panel"><h2>Website content setup required</h2><p>The website draft store has not been initialized for this deployment. Ask an administrator or developer to complete the one-time setup before staff begin editing.</p><p className="help-text">No live website content has been changed.</p></section></article>;
  return <article className="view website-view"><div className="view-heading"><div><p className="eyebrow">Website</p><h1>Pricing &amp; FAQs</h1><p>Manage the saved drafts used for a future immutable website release.</p></div><div className="cms-export"><button className="button secondary" onClick={()=>void downloadSnapshot()}>Export saved draft snapshot</button><small>Exports saved drafts only. Unsaved form changes are excluded.</small></div></div>
    <div className="cms-live-warning" role="note"><strong>Draft content — not the live website</strong>Saving here records a draft revision only. This milestone does not publish or deploy Sunny.</div>
    {pageError?<p className="inline-error" role="alert">{pageError}</p>:null}
    <fieldset className="panel cms-fieldset" disabled={pricing.status==="saving"}><div className="cms-section-heading"><div><h2>Pricing draft</h2><p className="help-text">Stable identifiers keep existing page and inquiry references intact. This milestone supports labels, amounts, and pricing modes; adding, deleting, or reordering pricing services remains a development task.</p></div><button type="button" className="button text" onClick={()=>void reload("pricing",pricing,setPricing)}>Reload saved pricing</button></div><div className="cms-pricing-list">{Object.entries(pricing.draft.values).map(([id,item])=><div className="cms-pricing-row" key={id}><label>Label<input value={item.label} onChange={(event)=>editPricing({...pricing.draft,values:{...pricing.draft.values,[id]:{...item,label:event.target.value}}})}/><code>{id}</code></label><label>Amount (USD)<input type="number" min="0" step="1" value={item.amount} onChange={(event)=>editPricing({...pricing.draft,values:{...pricing.draft.values,[id]:{...item,amount:Number(event.target.value)}}})}/></label><label>Pricing mode<select value={item.mode} onChange={(event)=>editPricing({...pricing.draft,values:{...pricing.draft.values,[id]:{...item,mode:event.target.value as PricingMode}}})}>{modes.map((mode)=><option value={mode} key={mode}>{modeLabel(mode)}</option>)}</select></label></div>)}</div><SaveBar editor={pricing} onSave={()=>void save("pricing",pricing,setPricing)} onDiscard={()=>void reload("pricing",pricing,setPricing,true)} onKeep={()=>void keepEditsOnLatest("pricing",pricing,setPricing)}/></fieldset>
    <fieldset className="cms-fieldset cms-faq-editor" disabled={faqs.status==="saving"}><FaqEditor title="Common FAQs" items={faqs.draft.common} onChange={(common)=>editFaqs({...faqs.draft,common})}/><FaqEditor title="Pricing FAQs" items={faqs.draft.pricing} onChange={(pricingItems)=>editFaqs({...faqs.draft,pricing:pricingItems})}/><div className="panel"><button type="button" className="button text" onClick={()=>void reload("faqs",faqs,setFaqs)}>Reload saved FAQs</button><SaveBar editor={faqs} onSave={()=>void save("faqs",faqs,setFaqs)} onDiscard={()=>void reload("faqs",faqs,setFaqs,true)} onKeep={()=>void keepEditsOnLatest("faqs",faqs,setFaqs)}/></div></fieldset>
    <section className="panel"><div className="cms-history-header"><div><h2>Revision history</h2><p className="help-text">Refreshing history never changes either form. Restore creates a new saved draft revision and warns before discarding unsaved changes.</p></div><button className="button text" onClick={()=>void refreshHistory()}>Refresh history</button></div><div className="cms-history-list">{history.map((revision)=><div className="cms-history-row" key={revision.revisionId}><div><strong>{revision.documentKey==="pricing"?"Pricing":"FAQs"} · revision {revision.sequence}</strong><p>{new Date(revision.createdAt).toLocaleString()} · {revision.actor.displayName}{revision.restoredFromRevisionId?" · restored":""}</p></div><button className="button secondary" disabled={(revision.documentKey==="pricing"?pricing:faqs).base.revisionId===revision.revisionId} onClick={()=>void restore(revision)}>Restore as new draft</button></div>)}</div></section>
  </article>;
}

function editor<T extends CmsContent>(base:CmsRevision<T>,messageText=`Saved draft revision ${base.sequence}.`):DocumentEditor<T>{return{base,draft:base.content,dirty:false,status:"saved",action:null,message:messageText};}
function FaqEditor({title,items,onChange}:{title:string;items:FaqItem[];onChange:(items:FaqItem[])=>void}){function move(index:number,direction:-1|1){const target=index+direction;if(target<0||target>=items.length)return;const next=[...items];[next[index],next[target]]=[next[target]!,next[index]!];onChange(next);}return <section className="panel"><h2>{title}</h2><div className="cms-faq-list">{items.map((item,index)=><div className="cms-faq-card" key={item.id}><label>Question<input value={item.question} onChange={(event)=>onChange(items.map((value)=>value.id===item.id?{...value,question:event.target.value}:value))}/></label><label>Answer<textarea value={item.answer} onChange={(event)=>onChange(items.map((value)=>value.id===item.id?{...value,answer:event.target.value}:value))}/></label><div className="cms-row-actions"><button type="button" className="button text" disabled={index===0} onClick={()=>move(index,-1)}>Move up</button><button type="button" className="button text" disabled={index===items.length-1} onClick={()=>move(index,1)}>Move down</button><button type="button" className="button text" onClick={()=>onChange(items.filter((value)=>value.id!==item.id))}>Remove</button></div></div>)}</div><button type="button" className="button secondary" onClick={()=>onChange([...items,{id:`faq_${crypto.randomUUID().replaceAll("-","")}`,question:"",answer:""}])}>Add FAQ</button></section>;}
function SaveBar<T extends CmsContent>({editor:current,onSave,onDiscard,onKeep}:{editor:DocumentEditor<T>;onSave:()=>void;onDiscard:()=>void;onKeep:()=>void}){return <div className="cms-actions"><div><p className={`cms-status ${current.status}`} role="status" aria-live="polite">{current.message}</p>{current.status==="conflict"?<div className="cms-conflict-actions"><button type="button" className="button secondary" onClick={onDiscard}>Discard my edits and load latest</button><button type="button" className="button secondary" onClick={onKeep}>Keep my edits on latest revision</button></div>:null}</div><button type="button" className="button primary" disabled={current.status==="saving"||!current.dirty} onClick={onSave}>{current.action==="save"?"Saving…":"Save draft"}</button></div>;}
function modeLabel(mode:PricingMode){return{exact:"Flat price",from:"Starting at",hourly:"Per hour",custom:"Custom quote"}[mode];}
function message(reason:unknown){return reason instanceof Error?reason.message:"The website draft request failed.";}
