export type PricingMode="exact"|"from"|"hourly"|"custom";
export type PricingDocument={schemaVersion:1;values:Record<string,{amount:number;mode:PricingMode;label:string}>};
export type FaqItem={id:string;question:string;answer:string};
export type FaqDocument={schemaVersion:1;common:FaqItem[];pricing:FaqItem[]};
export type CmsDocumentKey="pricing"|"faqs";
export type CmsContent=PricingDocument|FaqDocument;
export type CmsRevision<T extends CmsContent=CmsContent>={revisionId:string;documentKey:CmsDocumentKey;sequence:number;schemaVersion:number;content:T;actor:{id:string;displayName:string};createdAt:string;restoredFromRevisionId:string|null};
export type CmsReleaseStatus="queued"|"building"|"deploying"|"live"|"failed";
export type CmsRelease={releaseId:string;requestId:string;operationType:"publish"|"rollback";status:CmsReleaseStatus;schemaVersion:number;integrityHash:string;pricingRevisionId:string;faqRevisionId:string;actor:{id:string;displayName:string};requestedAt:string;hookTriggeredAt:string|null;runnerBuildId:string|null;sourceGitSha:string|null;workerVersionId:string|null;deploymentUrls:string[];deploymentTarget:Record<string,unknown>|null;startedAt:string|null;completedAt:string|null;failure:{code:string;message:string|null}|null;rollbackSourceReleaseId:string|null;rollbackSourceVersionId:string|null};
export type CmsPublicationState={configured:boolean;active:CmsRelease|null;live:CmsRelease|null;releases:CmsRelease[]};
export type CmsState={ok:true;initialized:boolean;documents:{pricing:CmsRevision<PricingDocument>|null;faqs:CmsRevision<FaqDocument>|null};publication:CmsPublicationState};
export type CmsHistory={ok:true;documentKey:CmsDocumentKey;revisions:CmsRevision[]};
