import { expect,test,type Page,type Route } from "@playwright/test";
const responder={id:"cms_manager",display_label:"CMS Manager",role:"manager",active:1,currently_available:0,heartbeat_at:null,expires_at:null};
const pricing={schemaVersion:1,values:{weddingDjCore:{amount:1700,mode:"from",label:"Wedding DJ/MC"}}};
const faqs={schemaVersion:1,common:[{id:"common_one",question:"Can I book one service?",answer:"Yes."}],pricing:[{id:"pricing_one",question:"Is this final?",answer:"It is a starting point."}]};
const revision=(key:"pricing"|"faqs",content:unknown,sequence=1)=>({revisionId:`${key}_${sequence}`,documentKey:key,sequence,schemaVersion:1,content,actor:{id:responder.id,displayName:responder.display_label},createdAt:"2026-09-28T12:00:00.000Z",restoredFromRevisionId:null});
async function mock(page:Page){let state={pricing:revision("pricing",pricing),faqs:revision("faqs",faqs)};await page.route("http://127.0.0.1:8787/**",async(route:Route)=>{const request=route.request();const path=new URL(request.url()).pathname;if(path==="/v1/internal/responders")return json(route,{ok:true,responders:[responder]});if(path==="/v1/internal/status")return json(route,{ok:true,chat:{state:"async",label:"Message",destinationUrl:null},activeResponders:[],messaging:{configured:false,provider:null},presenceTimeoutSeconds:120,eventCapacity:1});if(path==="/v1/internal/cms")return json(route,{ok:true,initialized:true,documents:state});if(path.endsWith("/revisions")){const key=path.includes("pricing")?"pricing":"faqs";return json(route,{ok:true,documentKey:key,revisions:[state[key]]});}if(path.endsWith("/restore")){const key=path.includes("pricing")?"pricing":"faqs";state={...state,[key]:revision(key,state[key].content,2)};return json(route,{ok:true,document:state[key]});}if(path==="/v1/internal/cms/snapshot")return json(route,{schemaVersion:1});if(path.startsWith("/v1/internal/cms/documents/")&&request.method()==="PUT"){const key=path.endsWith("pricing")?"pricing":"faqs";state={...state,[key]:revision(key,request.postDataJSON().content,2)};return json(route,{ok:true,document:state[key]});}return json(route,{ok:true});});}
async function login(page:Page){await page.goto("/");await page.getByLabel("Development API token").fill("test-token");await page.getByRole("button",{name:"Connect to Local Operations"}).click();await page.getByLabel("Act as responder").selectOption(responder.id);await page.getByRole("button",{name:"Open Staff Workspace"}).click();}
test("manager edits website drafts with no publish control",async({page})=>{await mock(page);await login(page);await page.getByRole("link",{name:"Website"}).click();await expect(page.getByText("Draft content — not the live website")).toBeVisible();await expect(page.getByRole("button",{name:/publish/i})).toHaveCount(0);await page.getByLabel("Amount (USD)").fill("1800");await page.getByLabel("Pricing mode").selectOption("exact");await page.getByRole("button",{name:"Save draft"}).first().click();await expect(page.getByText("Saved as a new draft revision.").first()).toBeVisible();await page.getByRole("button",{name:"Add FAQ"}).first().click();await expect(page.getByLabel("Question")).toHaveCount(3);await expect(page.locator("body")).not.toHaveCSS("overflow-x","scroll");});
async function json(route:Route,body:unknown){await route.fulfill({status:200,contentType:"application/json",body:JSON.stringify(body)});}
